### ISSUE TITLE
Ошибка парсинга rss

### ISSUE THREAD

**Issue by Snowsides** [turboext/components#83]
При запуске локально сообщение об ошибке — StatusCodeError: 500 - "Ошибка парсинга rss".
Формат правильный. При запуски имеющихся компонентов так же "Ошибка парсинга rss".
Что поправить?

**Comment by Peccansy** [comment]
Добрый день! Боюсь, что проблема со стороны бекенда. Наш дежурный будет разбираться с этим и мы вернёмся в этот issue.

**Comment by vmstukalov** [comment]
Та же ошибка повторяется попеременно с RequestError: Error: socket hang up

RequestError: Error: socket hang up
    at new RequestError (/Users/vitaly/IdeaProjects/TurboComponents/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/vitaly/IdeaProjects/TurboComponents/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/vitaly/IdeaProjects/TurboComponents/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/vitaly/IdeaProjects/TurboComponents/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:486:12)
    at Request.onRequestError (/Users/vitaly/IdeaProjects/TurboComponents/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketOnEnd (_http_client.js:493:9)
    at TLSSocket.emit (events.js:326:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
